name: flutter_qr_code_reader
description: Flutter QR Code Reader
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_qr_bar_scanner: ^3.0.2
  http: ^0.13.5
  qr_flutter: ^2.0.0
  string_splitter: ^1.0.0+1
  url_launcher: ^6.1.6
  flutter_beep: ^1.0.0
  flutter_vibrate: ^1.3.0
  wakelock: ^0.5.6
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  qr_code_scanner: ^1.0.1
  awesome_dialog: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true